maint: Use ansys actions in workflow
ansys/ansys-api-meshing-prime pull request #10
Opened 2023-06-30 13:16 UTC by AlejandroFernandezLuces

2023-06-30 14:47 UTC, RobPasMue reviewed
@AlejandroFernandezLuces - base yourself on https://github.com/ansys/ansys-templates/blob/feat/template-api/src/ansys/templates/python/ansys_api/%7B%7B%20cookiecutter.__project_name_slug%20%7D%7D/.github/workflows/ci.yml

I recommend you to follow this workflow and replicate it. This is going to be the new standard

2023-06-30 21:37 UTC, ninad-kamat submitted a review, later dismissed

2023-06-30 21:37 UTC, ninad-kamat commented on .github/workflows/ci.yml
> +      - "*"
Keep this as `v*`. We only want to run when a release tag is pushed.

2023-06-30 21:40 UTC, ninad-kamat commented on .github/workflows/ci.yml
> +      - "*"
This is a protected tag in policies as well.

2023-07-03 05:35 UTC, RobPasMue requested changes

2023-07-03 05:35 UTC, RobPasMue commented on .github/workflows/ci.yml
> +          twine-token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
```suggestion
      - name: "Release to the public PyPI"
        uses: ansys/actions/release-pypi-public@v4
        with:
          library-name: ${{ env.LIBRARY_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.TWINE_TOKEN }}
```

2023-07-03 05:35 UTC, RobPasMue commented on .github/workflows/ci.yml
> +          twine-token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
It has to be released to the public PyPI

2023-07-03 07:26 UTC, RobPasMue approved these changes

2023-07-03 07:27 UTC, merged